# permissions to do viewer observatoria.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: observatorium-viewer-role
rules:
- apiGroups:
  - observatorium.observatorium
  resources:
  - observatoria
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - observatorium.observatorium
  resources:
  - observatoria/status
  verbs:
  - get
