apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: jaeger-all-in-one
  name: jaeger-admin
  namespace: observatorium
spec:
  ports:
  - name: admin-http
    port: 14269
    targetPort: 14269
  selector:
    app.kubernetes.io/name: jaeger-all-in-one
