apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: thanos-receive-controller
  namespace: observatorium
spec:
  endpoints:
  - port: http
  selector:
    matchLabels:
      app.kubernetes.io/name: thanos-receive-controller
