apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: observatorium-querier-cache
  name: observatorium-cache
  namespace: observatorium
spec:
  ports:
  - name: cache
    port: 9090
    targetPort: 9090
  selector:
    app.kubernetes.io/name: observatorium-querier-cache
